spring:
  application:
    name: f1c-server
  docker:
    compose:
      enabled: false
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:54323/f1c?rewriteBatchedInserts=true
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          response-format:
            type: JSON_OBJECT
