spring:
  application:
    name: f1c-server
  docker:
    compose:
      enabled: false
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:54323/f1c?reWriteBatchedInserts=true
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
