### Get Race Schedules By Year And Month

GET {{API_URL}}/schedules?year=2024&month=11

### Get Latest Race Schedule

GET {{API_URL}}/schedules/latest

### Get Latest Race Schedule By Race Type

GET {{API_URL}}/schedules/latest?raceType=Qualifying

### Get Latest Race Schedule By Wrong Race Type

GET {{API_URL}}/schedules/latest?raceType=Invalid

### Get Latest Finished Race Schedule

GET {{API_URL}}/schedules/latest/finished

### Get Latest Finished Race Schedule By Race Type

GET {{API_URL}}/schedules/latest/finished?raceType=FirstPractice
